spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  sql:
    init:
      data-locations: classpath:data.sql
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}