spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  jwtSecret: secretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000
  usedTimezone: "Europe/Warsaw"
  visitLengthMin: 5