spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    defer-datasource-initialization: ${SPRING_JPA_DATABASE-DEFER-DATASOURCE-INITIALIZATION}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}
      data-locations: classpath:data.sql

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}
  usedTimezone: ${USED_TIMEZONE}
  visitLengthMin: ${VISIT_LENGTH_MIN}
