spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    defer-datasource-initialization: ${SPRING_JPA_DATABASE-DEFER-DATASOURCE-INITIALIZATION}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}
      data-locations: classpath:data.sql
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}